const postList=document.querySelector('#post-list'),postForm=document.querySelector('#post-editor'),postBody=document.querySelector('#post-body'),postFeedback=document.querySelector('#post-feedback');let posts=[],editingId=null;
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=s=>escapeHtml(s).replace(/\*\*([^*\n]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*\n]+)\*/g,'<em>$1</em>');
const inline=s=>{let out='',last=0;for(const match of String(s).matchAll(/\[([^\]]{1,120})\]\((https?:\/\/[^\s)]+)\)/g)){out+=format(s.slice(last,match.index))+`<a href="${escapeHtml(match[2])}" rel="noopener noreferrer">${escapeHtml(match[1])}</a>`;last=match.index+match[0].length}return out+format(s.slice(last))};
function markdownToHtml(source){const out=[];let list=[];const flush=()=>{if(list.length){out.push('<ul>'+list.map(x=>'<li>'+inline(x)+'</li>').join('')+'</ul>');list=[]}};for(const block of String(source||'').split(/\n\s*\n/)){const lines=block.split('\n').filter(Boolean);if(!lines.length)continue;for(const line of lines){if(line.startsWith('## ')){flush();out.push('<h2>'+inline(line.slice(3))+'</h2>')}else if(line.startsWith('### ')){flush();out.push('<h3>'+inline(line.slice(4))+'</h3>')}else if(line.startsWith('- ')){list.push(line.slice(2))}else{flush();out.push('<p>'+inline(line)+'</p>')}}flush()}return out.join('')}
function toMarkdown(node){if(node.nodeType===Node.TEXT_NODE)return node.textContent.replace(/\s+/g,' ');if(node.nodeType!==Node.ELEMENT_NODE)return '';const tag=node.tagName,children=()=>[...node.childNodes].map(toMarkdown).join('');if(tag==='BR')return '\n';if(['B','STRONG'].includes(tag))return '**'+children()+'**';if(['I','EM'].includes(tag))return '*'+children()+'*';if(tag==='A'){const href=node.getAttribute('href')||'';return /^https?:\/\//i.test(href)?`[${children()}](${href.replace(/[()\s]/g,'')})`:children()}if(tag==='H2')return '\n\n## '+children()+'\n\n';if(tag==='H3')return '\n\n### '+children()+'\n\n';if(tag==='LI')return '- '+children()+'\n';if(tag==='UL')return '\n'+children()+'\n';if(['DIV','P'].includes(tag))return children()+'\n\n';return children()}
function showList(){postList.replaceChildren();if(!posts.length){const p=document.createElement('p');p.textContent='No posts yet. Write the first one when you are ready.';postList.append(p);return}for(const post of [...posts].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))){const row=document.createElement('div');row.className='post-row';const info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small');title.textContent=post.title;detail.textContent=(post.status==='published'?'Published':'Draft')+' · Updated '+new Date(post.updatedAt).toLocaleDateString('en-GB');info.append(title,detail);const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.addEventListener('click',()=>openPost(post));row.append(info,edit);postList.append(row)}}
async function loadPosts(){try{const response=await fetch('/api/admin/posts');if(!response.ok)throw Error('Could not load posts.');posts=await response.json();showList()}catch(error){postList.textContent=error.message}}
function openPost(post){editingId=post?.id||null;document.querySelector('#post-form-title').textContent=post?'Edit post':'New post';document.querySelector('#post-title').value=post?.title||'';document.querySelector('#post-excerpt').value=post?.excerpt||'';document.querySelector('#post-status').value=post?.status||'draft';postBody.innerHTML=markdownToHtml(post?.content||'');postForm.hidden=false;postFeedback.textContent='';postForm.scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelector('#new-post').addEventListener('click',()=>openPost(null));document.querySelector('#cancel-post').addEventListener('click',()=>{postForm.hidden=true;editingId=null});
for(const button of document.querySelectorAll('[data-format]'))button.addEventListener('click',()=>{postBody.focus();const action=button.dataset.format;if(action==='bold'||action==='italic')document.execCommand(action,false);if(action==='h2')document.execCommand('formatBlock',false,'h2');if(action==='ul')document.execCommand('insertUnorderedList',false);if(action==='link'){const url=prompt('Link address (https://…)');if(url&&/^https?:\/\//i.test(url))document.execCommand('createLink',false,url)}});
postBody.addEventListener('paste',event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'))});
postForm.addEventListener('submit',async event=>{event.preventDefault();postFeedback.textContent='Saving…';const body={id:editingId,title:document.querySelector('#post-title').value.trim(),excerpt:document.querySelector('#post-excerpt').value.trim(),content:toMarkdown(postBody).trim().replace(/\n{3,}/g,'\n\n'),status:document.querySelector('#post-status').value};try{const response=await fetch('/api/admin/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save.');editingId=data.id;await loadPosts();postFeedback.textContent=data.status==='published'?'Published. View at /blog/'+data.slug:'Draft saved. Only you can see it.'}catch(error){postFeedback.textContent=error.message}});
loadPosts();
