const groups=[['Welcome',['heroTitle','heroCredential','heroIntro']],['Counselling and practice',['sectionTitle','sectionIntro','supportTitle','supportIntro','supportItems','aboutTitle','aboutText','practiceDetails']],['Sessions and fees',['approachTitle','approachText','introTitle','introText','price','priceNote','availability']],['Contact',['contactTitle','contactText','phone','email','location']],['Blog page',['blogTitle','blogIntro']]];
const labels={sectionTitle:'Section heading',sectionIntro:'Introduction to counselling',practiceDetails:'Practice and online session details',heroTitle:'Main heading',heroCredential:'Qualification and membership line',heroIntro:'Opening paragraph',aboutTitle:'About heading',aboutText:'About paragraph',supportTitle:'Support heading',supportIntro:'Support introduction',supportItems:'Areas of support (one per line)',approachTitle:'Sessions heading',approachText:'Sessions paragraph',introTitle:'Introductory call heading',introText:'Introductory call paragraph',price:'Price',priceNote:'Price description',availability:'Availability',contactTitle:'Contact heading',contactText:'Contact paragraph',phone:'Phone number',email:'Public email (optional)',location:'Location',blogTitle:'Blog page title',blogIntro:'Blog page introduction'};
const form=document.querySelector('#editor'),status=document.querySelector('#status');let keys=[],baseline='',saveButton;
function values(){const data={};for(const key of keys)data[key]=key==='supportItems'?form.elements[key].value.split('\n').map(s=>s.trim()).filter(Boolean):form.elements[key].value.trim();return data}
function refreshSave(){if(!saveButton)return;const dirty=JSON.stringify(values())!==baseline;saveButton.disabled=!dirty;saveButton.textContent=dirty?'Save website changes':'All changes saved';if(dirty&&status.textContent==='Saved. The website now shows these changes.')status.textContent='Unsaved changes'}
form.addEventListener('input',refreshSave);
fetch('/api/content').then(r=>r.json()).then(data=>{keys=Object.keys(data);for(const [heading,fields] of groups){const group=document.createElement('div');group.className='editor-group';const h=document.createElement('h2');h.textContent=heading;group.append(h);form.append(group);for(const key of fields){if(!(key in data))continue;const wrap=document.createElement('div');wrap.className='editor-field'+(key==='price'||key==='priceNote'||key==='phone'||key==='email'?'':' is-wide');const label=document.createElement('label');label.htmlFor=key;label.textContent=labels[key]||key;const field=document.createElement(['price','priceNote','phone','email','availability'].includes(key)?'input':'textarea');field.id=key;field.name=key;field.value=Array.isArray(data[key])?data[key].join('\n'):data[key];if(field.tagName==='TEXTAREA')field.rows=key==='supportItems'?6:Math.max(2,Math.min(5,Math.ceil(field.value.length/95)));wrap.append(label,field);form.append(wrap)}}const actions=document.createElement('div');actions.className='editor-actions';const button=document.createElement('button');button.type='submit';button.className='button';saveButton=button;actions.append(status,button);form.append(actions);baseline=JSON.stringify(values());refreshSave()}).catch(()=>status.textContent='Could not load the website text.');
form.addEventListener('submit',async e=>{e.preventDefault();status.textContent='Saving…';saveButton.disabled=true;const data=values();try{const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error((await r.json()).error);baseline=JSON.stringify(data);status.textContent='Saved. The website now shows these changes.'}catch(err){status.textContent='Could not save: '+err.message}finally{refreshSave()}});
document.querySelector('#logout').addEventListener('click',async()=>{await fetch('/api/session',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});location.replace('/admin/')});
for(const tab of document.querySelectorAll('[data-tab]'))tab.addEventListener('click',()=>{for(const item of document.querySelectorAll('[data-tab]')){const active=item===tab;item.classList.toggle('is-active',active);item.setAttribute('aria-selected',String(active))}document.querySelector('#site-panel').hidden=tab.dataset.tab!=='site';document.querySelector('#blog-panel').hidden=tab.dataset.tab!=='blog'});
